server:
  port: 8082

spring:
  application:
    name: ms-master
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
